# Generated by Django 5.1.5 on 2025-02-09 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_created_at_movie_description_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
