# Generated by Django 5.1.5 on 2025-02-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
