# Generated by Django 5.1.5 on 2025-02-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_created_at_movie_tmdb_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieTest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
