# Generated by Django 5.1.5 on 2025-02-09 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_movie_movietest_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('poster_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MovieTest',
        ),
    ]
