# Generated by Django 5.1.5 on 2025-02-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
    ]
